#!/usr/bin/env python
##This will work in development on a relative folder basis
##It will then work when installed in site-packages on a target system
##where the runner script is in /usr/bin (or wherever)
##
##So, you don't need anything special - no fancy path tricks.
import logging
from optparse import OptionParser

import daemon

from canape.main import Canape
from canape.xmlrpc import CanapeXMLRPCServer

usage = "usage: %prog [options] arg"
parser = OptionParser(usage,  version="%prog 1.0")

parser.add_option("-D", "--daemon", action="store_true", dest="daemon",
                  default=False, help="Start canape as a daemon")

parser.add_option("--xmlrpc",
                  action="store_true", dest="xmlrpc",
                  help="Launch xmlrpc interface")

parser.add_option("--only-xmlrpc",
                  action="store_true", dest="onlyxmlrpc",
                  help="Launch xmlrpc interface")

parser.add_option("-l", "--log", dest='logfile',
                  metavar="FILE", help="write logging output to FILE")

parser.add_option("-v", "--verbose",
                  action="store_true", dest="verbose",
                  help="Log all info [default]")

parser.add_option("-d", "--debug",
                  action="store_true", dest="debug",
                  help="Log all message")
(options, args) = parser.parse_args()

loglevel = logging.ERROR
if options.verbose is True:
    loglevel = logging.INFO
if options.debug is True:
    loglevel = logging.DEBUG

if options.logfile is None:
    logging.basicConfig(level = loglevel)
    files_preserve=None
else:
    logger = logging.getLogger()
    handler = logging.FileHandler(options.logfile)
    handler.setLevel(loglevel)
    logger.addHandler(handler)
    logger.setLevel(loglevel)
    files_preserve=[handler.stream]

if options.onlyxmlrpc is True:
    s = CanapeXMLRPCServer()
    s.daemon = False
    s.run()
else:
    canape = Canape()
    if not options.daemon:
        canape.check()
    else:
        with daemon.DaemonContext(files_preserve=files_preserve):
            canape.daemon_run()
